<?php $_filterItems = $block->getAppliedFilters(); ?>
<?php if (!empty($_filterItems)): ?>
    <?php
    $_state = [];
    foreach ($_filterItems as $_filterItem) {
        $filterName = $_filterItem->getName();
        if (is_object($filterName)) {
            $filterName = $filterName->getText();
        }

        $filterLabel = $_filterItem->getLabel();
        $filterLabelText =  is_object($filterLabel) ?
            $filterLabel->getText() : (string) $filterLabel;

        $_state[$filterName][$filterLabelText] = [
            'label' => $filterLabel,
            'url' => $_filterItem->getRemoveUrl()
        ];
    }
    ?>
<ul class="filter-active">
    <?php foreach ($_state as $_filterName => $_items): ?>
        <li>
            <span class="filter-label">
                <?= $block->escapeHtml(__($_filterName)); ?>
            </span>
        <?php foreach ($_items as $_filter): ?>
            <?php
                $label = $block->stripTags($_filter['label']);
                $removeUrl = $_filter['url'];

                $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
                $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
                $currencyCode = $storeManager->getStore()->getCurrentCurrency(); 
                $currencySymbol = $currencyCode->getCurrencySymbol();
                $label = str_replace([$currencySymbol.'.', $currencySymbol], '', $label);
            ?>
            <div class="state-item">
                <span class="state-item-name" title="<?= $block->escapeHtmlAttr($label) ?>">
                    <?= $block->escapeHtml($label) ?>
                </span>
                <span class="state-item-remove">
                    <span class="state-item-icon-cancel"></span>
                </span>
                <a class="state-item-remove-url" href="<?= $block->escapeUrl($removeUrl) ?>"></a>
            </div>
        <?php endforeach; ?>
        </li>
    <?php endforeach; ?>
    <li>
        <a class="filter-active-item-clear-all"
           title="<?= $block->escapeHtmlAttr(__('Clear All')) ?>"
           href="<?= $block->escapeUrl($block->getClearAllUrl()) ?>">
            <span><?= $block->escapeHtml(__('Clear All')) ?></span>
        </a>
    <li>
</ul>
<?php endif; ?>
