<ol class="items list">
    <?php foreach ($filterItems as $filterItem):
        if (method_exists($filterItem, 'isShowActiveDisabled') && $filterItem->isShowActiveDisabled()) {
            continue;
        };
            $title = strlen($filterItem->getLabel()) > 20 ? $filterItem->getLabel() : '';
            $checkedAttribute = $filterItem->getActive() ? 'checked="checked"' : '';
        ?>
        <li class="item">
            <div class="swissup-filter-item-checkbox">
                <input type="checkbox" class="swissup-layered-checkbox" <?= /* @noEscape */ $checkedAttribute ?>>
                <div class="swissup-aln-content"></div>
            </div>
            <a href="<?= $block->escapeUrl($filterItem->getActionUrl())?>"
               class="swissup-aln-item"
               title="<?= $block->escapeHtmlAttr($title) ?>"
               data-request-var="<?= $block->escapeHtmlAttr($filterItem->getRequestVar()) ?>"
               data-value="<?= $block->escapeHtmlAttr($filterItem->getValue()) ?>"
                rel="nofollow"
            >
                <span class="swissup-option-label">
                <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
                    $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
                    $currencyCode = $storeManager->getStore()->getCurrentCurrency(); 
                    $currencySymbol = $currencyCode->getCurrencySymbol();
                    $filterLabel = str_replace([$currencySymbol.'.', $currencySymbol], '', $filterItem->getLabel());
                    echo $block->escapeHtml($filterLabel) ?>
                </span>
                <?php if ($filterItem->hasCount()):
                    $plusClass = ' swissup-count-' . ($filterItem->getPlus() ? 'red' : 'green');
                    ?>
                    <span class="count swissup-option-count<?= /* @noEscape */ $plusClass ?>">
                        <?= $block->escapeHtml(($filterItem->getPlus() ? '+' : '') . $filterItem->getCount()) ?>
                    </span>
                <?php endif; ?>
            </a>
        </li>
    <?php endforeach ?>
</ol>
